# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d087cc975e8d672bfad0e03f248db8d9d52cce1e46a4d3ac52b4d68039c30a31d9060e9da3f0384bff9d41edd163f3eef9ad579edee1c539029c4f8c00464cc

test:
  secret_key_base: 3aa3adf0ddf0ada293faff59d3a99806d6c24dc5547fbdb636f2a47a76602602b82d2ae61e80e34b07ca789bfcc25c6d6060e827055120015d54a69414d2211c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
